"""`savvy assemble` against synthetic audio and footage. No API key, no network.

Same pattern as test_pipeline.py: everything is generated by ffmpeg at test
time. A click track exercises the BPM estimator; a tagged copy exercises the
tag path; a small flagged crate exercises the EDL writer against
hand-calculated timecodes.
"""
import argparse
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from savvy import beatgrid, config, db, edl, media  # noqa: E402
from savvy.stages import assemble  # noqa: E402


def ns(**kw):
    return argparse.Namespace(**kw)


# --------------------------------------------------------------------------
# synthetic click track and the estimators


@pytest.fixture(scope="session")
def click_track(tmp_path_factory):
    """8s of 1000 Hz beeps at 120 BPM - one ~0.13s beep every 0.5s.

    aevalsrc multiplies a 1000 Hz sine by a 2 Hz square gate, so the period is
    0.5s and the first beep lands at t=0. No tags, which is what makes this
    exercise the estimator.
    """
    d = tmp_path_factory.mktemp("track")
    p = d / "click.wav"
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i",
                    r"aevalsrc=sin(2*PI*1000*t)*gt(sin(2*PI*t/0.5)\,0.7)"
                    ":d=8:s=11025", str(p)], check=True)
    return p


def test_detect_bpm_estimates_click_track(click_track):
    bpm, src = beatgrid.detect_bpm(click_track)
    assert src == "estimated", "a synthetic wav has no tag"
    assert abs(bpm - 120) <= 5


def test_detect_offset_finds_first_beat(click_track):
    offset, src = beatgrid.detect_offset(click_track, 120)
    assert src == "estimated"
    assert abs(offset) < 0.5, "the first beep lands at t=0"


def test_override_beats_tag_and_estimate(click_track):
    assert beatgrid.detect_bpm(click_track, override=140) == (140.0, "override")
    assert beatgrid.detect_offset(click_track, 120, override=1.5) == (1.5, "override")


def test_detect_bpm_prefers_tag_over_estimate(click_track, tmp_path):
    """A DJ tool's tag wins - that is the whole point of the priority order."""
    mp3 = tmp_path / "tagged.mp3"
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", str(click_track),
                    "-b:a", "96k", str(mp3)], check=True)
    from mutagen.id3 import ID3, TBPM
    tags = ID3(mp3)
    tags.add(TBPM(encoding=3, text=["123"]))
    tags.save(mp3)
    bpm, src = beatgrid.detect_bpm(mp3)
    assert src == "tag"
    assert bpm == 123.0


def test_beat_grid_spacing():
    grid = beatgrid.beat_grid(120, 0.0, 4.0)
    assert grid == [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]


# --------------------------------------------------------------------------
# EDL writer


def test_write_cmx3600_uses_source_and_sequence_fps(tmp_path):
    """src timecodes are at the original's 30 fps, record at the 24 fps cut."""
    ev = edl.Event(reel="CLIP1", source_path=Path("/x/CLIP1.mp4"),
                   src_in=0.5, src_out=4.5, rec_in=0.0, rec_out=4.0, src_fps=30)
    out = tmp_path / "a.edl"
    edl.write_cmx3600([ev], 24.0, out)
    text = out.read_text()
    assert text.startswith("TITLE: A\nFCM: NON-DROP FRAME")
    assert "00:00:00:15 00:00:04:15 00:00:00:00 00:00:04:00" in text
    assert "* FROM CLIP NAME: CLIP1.mp4" in text

# --------------------------------------------------------------------------
# the whole stage against a flagged crate


@pytest.fixture
def crate_env(tmp_path, click_track):
    """Three 30 fps clips, flagged ranges 0.5-5.5s, ratings 5, 4, 3."""
    cfg = dict(config.DEFAULTS)
    cfg.update({"work_dir": str(tmp_path / "work")})
    con = db.connect(cfg)
    src = tmp_path / "src" / "DELTA REEL"
    src.mkdir(parents=True)
    for i in range(3):
        p = src / f"clip{i + 1}.mp4"
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i",
                        "testsrc2=size=320x180:rate=30:duration=6",
                        "-pix_fmt", "yuv420p", str(p)], check=True)
        cur = con.execute("INSERT INTO media (src_path,event,bytes,state) "
                          "VALUES (?,?,0,'proxied')", (str(p), "DELTA REEL"))
        con.execute("INSERT INTO clips (media_id,start,end,state,score,flagged,"
                    "my_rating) VALUES (?,?,?,'scored',?,1,?)",
                    (cur.lastrowid, 0.5, 5.5, 8 - i, 5 - i))
    con.commit()
    yield cfg, con, click_track
    con.close()


def test_edl_events_and_timecodes(crate_env):
    """bpm=120, offset=0, bars=2 -> 4.0s segments; an 8s track -> 2 events.

    Sources run at 30 fps and the sequence at 24, so src and rec timecodes are
    computed on different frame rates - which is exactly the probe_fps path.
    """
    cfg, con, track = crate_env
    out = Path(cfg["work_dir"]) / "assemble.edl"
    assemble.run(cfg, con, ns(track=str(track), bpm=120, offset=0.0,
                              bars=2, fps=24, out=str(out)))
    lines = [l for l in out.read_text().splitlines() if l and l[0].isdigit()]
    assert len(lines) == 2
    # event 1 takes clip1 (highest rating): src 0.5-4.5s at 30fps, rec 0-4s
    assert lines[0].startswith("001  CLIP1")
    assert "00:00:00:15 00:00:04:15 00:00:00:00 00:00:04:00" in lines[0]
    # event 2 takes clip2, the record timeline continues at 4-8s
    assert lines[1].startswith("002  CLIP2")
    assert "00:00:00:15 00:00:04:15 00:00:04:00 00:00:08:00" in lines[1]


def test_edl_uses_original_filenames_for_relink(crate_env):
    cfg, con, track = crate_env
    out = Path(cfg["work_dir"]) / "assemble.edl"
    assemble.run(cfg, con, ns(track=str(track), bpm=120, offset=0.0,
                              bars=2, fps=24, out=str(out)))
    text = out.read_text()
    assert "* FROM CLIP NAME: clip1.mp4" in text
    assert "* FROM CLIP NAME: clip2.mp4" in text


def test_stops_when_clips_run_out(tmp_path, click_track, capsys):
    """One clip covers the first segment only; stop, never loop or reuse."""
    cfg = dict(config.DEFAULTS)
    cfg.update({"work_dir": str(tmp_path / "work")})
    con = db.connect(cfg)
    p = tmp_path / "only.mp4"
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i",
                    "testsrc2=size=320x180:rate=24:duration=6",
                    "-pix_fmt", "yuv420p", str(p)], check=True)
    cur = con.execute("INSERT INTO media (src_path,event,bytes,state) "
                      "VALUES (?,?,0,'proxied')", (str(p), "EVENT"))
    con.execute("INSERT INTO clips (media_id,start,end,state,score,flagged,"
                "my_rating) VALUES (?,?,?,'scored',7,1,4)",
                (cur.lastrowid, 0.0, 6.0))
    con.commit()
    out = Path(cfg["work_dir"]) / "assemble.edl"
    assemble.run(cfg, con, ns(track=str(click_track), bpm=120, offset=0.0,
                              bars=2, fps=24, out=str(out)))
    lines = [l for l in out.read_text().splitlines() if l and l[0].isdigit()]
    assert len(lines) == 1
    assert "uncovered" in capsys.readouterr().out
    assert "00:00:04:00" in lines[0], "one 4s event, then the EDL stops"


def test_skips_cloud_only_originals(crate_env, monkeypatch, capsys):
    """A placeholder passes exists(), so the cloud check must do the work."""
    from savvy import storage
    cfg, con, track = crate_env
    monkeypatch.setattr(storage, "is_cloud_only_path", lambda p: True)
    with pytest.raises(SystemExit):
        assemble.run(cfg, con, ns(track=str(track), bpm=120, offset=0.0,
                                  bars=2, fps=24, out="unused.edl"))
    assert "online-only" in capsys.readouterr().out


